---
- name: Install Docker
  hosts: all
  sudo: yes
  roles:
    - angstwad.docker_ubuntu

- hosts: all
  sudo: yes
  tasks:
  - include_vars: vars/main.yml
  - name: Create persistent data directory for MySql
    file: path=/data state=directory mode=0755
  - name: Start MySql docker container
    docker:
      name: mysql
      image: mysql:5.7.8
      pull: always
      state: reloaded
      restart_policy: always
      volumes:
      - /data:/var/lib/mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
  - name: Run tracks application
    docker:
      name: tracks
      image: mattfritz/tracks:2.3.0
      pull: always
      state: reloaded
      restart_policy: always
      links:
      - "mysql:mysql"
      expose: 3000
      ports:
        - "0.0.0.0:80:3000"
      env:
        MYSQL_HOST: mysql
        MYSQL_PASSWORD: "{{ mysql_password }}"
        APP_PASSWORD_SALT: "{{ app_password_salt }}"
        APP_SECRET_TOKEN: "{{ app_secret_token }}"
        RAILS_ENV: production
